name: 05 - Expressions & runner information
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Verify OS and arch
        id: osArch
        run: |
         echo "Operating system: ${{ runner.os }}"
         echo "System architecture: ${{ runner.arch }}"
      - name: Operators
        id: operators
        run: echo "${{ 2 > 1 }}"
      - name: Inspect the Github Context
        id: ghContext
        # run: echo "${{ toJSON(github) }}"
        run: echo $JSON # Workaround for https://github.com/actions/runner/issues/1656
        env:
          JSON: ${{ toJSON(github) }}
      - name: Event and actor
        id: eventActor
        run: |
         echo "Triggering event: ${{ github.event_name }}"
         echo "Launched by: ${{ github.actor }}"
      - name: Object filter
        id: stepsContext
        run: |
          echo "${{ toJSON(steps) }}"
          echo "${{ join(steps.*.conclusion) }}"
