name: 06 - Variables and secrets
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CHOSEN_PILL: ${{ vars.PILL_COLOR || 'Blue' }}
jobs:
  the-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Neos choice storage
        run: echo "NEOS_CHOICE=${{ env.CHOSEN_PILL }}" >> "$GITHUB_ENV"
      - name: Pass value to the next step
        run: |
          echo "Neo, you have chosen pill: ${{ env.NEOS_CHOICE }}"
      - name: Know the truth
        if: ${{ env.CHOSEN_PILL == 'Red' }}
        run: |
          echo "Neo, reality is not what you think it is"
          echo "I'll tell you a secret: ${{ secrets.EVERYTHING_IS_A_LIE }}"
          echo "${{ secrets.EVERYTHING_IS_A_LIE }}"  | sed 's/./& /g' 
      - name: Keep on with my life
        if: ${{ env.CHOSEN_PILL != 'Red' }}
        run: echo "Neo, keep on with your happy life"
