name: 07 - Inputs and outputs
on:
  workflow_dispatch:
    inputs:
      number-of-dice:
        type: choice
        options:
          - one
          - two
        default: two
        description: The number of dice
jobs:
  dice-roll:
    outputs:
      die1: ${{ steps.firstDie.outputs.die1 }}
      die2: ${{ steps.secondDie.outputs.die2 }}
    runs-on: ubuntu-latest
    steps:
      - name: how many dice?
        run: echo "There are ${{inputs.number-of-dice}} dice"
      - name: Generate die 1
        id: firstDie
        run: echo "die1=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"
      - name: Generate die 2
        if: ${{ inputs.number-of-dice == 'two' }}  
        id: secondDie
        run: echo "die2=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"
  summary:
    runs-on: ubuntu-latest
    needs: dice-roll
    steps:
      - name: Summary header and 1st die
        run: |
         echo "# :game_die: The result is:" >> $GITHUB_STEP_SUMMARY
         echo die1: ${{needs.dice-roll.outputs.die1}} >> $GITHUB_STEP_SUMMARY
      - name: 2nd die summary
        if: ${{ inputs.number-of-dice == 'two' }}
        run: |
          echo die2: ${{needs.dice-roll.outputs.die2}} >> $GITHUB_STEP_SUMMARY
         